= ye (Yocto Explorer)

== Introduction

`ye` is a command line tool to ease the manipulation of files under
the directory structure adopted by O.S. Systems to organize projects
that use the Yocto Project.  `ye` provides means to quickly locate
files and directories into projects' directory tree, and act on them.

== Usage

....
$ ye -h
Usage: ye <command> [ <options> ]

f [-e] <regex>
find [-e] <regex>
    Locate paths (in the "sources" directory) that match the given
    expression <regex>.  <regex> is case insensitive and implicitly
    surrounded by '.*'.  -e disables the implicit use of '.*' around
    the given <regex>.  Note that, unless <regex> contains /, matching
    is attempted on filenames only (not on dirnames).  If <regex>
    contains /, matching is attempted on the full path.

v [-e] <regex>
view [-e] <regex>
    Shortcut to find & view.  If multiple files are found, a prompt for
    files will be displayed (but not for actions).

e [-e] <regex>
edit [-e] <regex>
    Shortcut to find & edit.  If multiple files are found, a prompt for
    files will be displayed (but not for actions).

sf [-e] <regex>
sysroot-find [-e] <regex>
    Locate paths (in the "sysroots" directory) that match the given
    expression <regex>.  <regex> is case insensitive and implicitly
    surrounded by '.*'.  -e disables the implicit use of '.*' around
    the given <regex>.  Note that, unless <regex> contains /, matching
    is attempted on filenames only (not on dirnames).  If <regex>
    contains /, matching is attempted on the full path.

pf [-e] <regex>
pkg-find [-e] <regex>
    Like 'find', but for packages.

pv [-e] <regex>
pkg-view [-e] <regex>
    Shortcut to pkg-find & view.  If multiple packages are found, a
    prompt for packages will be displayed (but not for actions).

pi [-e] <regex>
pkg-info [-e] <regex>
    Shortcut to pkg-find & info.  If multiple packages are found, a
    prompt for packages will be displayed (but not for actions).

ps [-e] <regex>
pkg-scripts [-e] <regex>
    List scripts for package that matches <regex>.  In case of multiple
    matches, ye will prompt for a specific package. <regex> is case
    insensitive and implicitly surrounded by '.*'.  -e disables the
    implicit use of '.*' around the given <regex>.

px [-e] [-c] <regex> [<file>]
pkg-extract [-e] [-c] <regex> [<file>]
    Extract package that matches <regex>.  In case of multiple matches,
    ye will prompt for a specific package. <regex> is case insensitive
    and implicitly surrounded by '.*'.  -e disables the implicit use
    of '.*' around the given <regex>.
    If <file> is provided, ye will extract <file> only, otherwise the
    whole package content will be extracted to a directory named after
    the package filename (without extension).  <file> must match the exact
    file name in the package (usually starts with ./).
    -c is specific to .deb and .ipk packages -- ye will extract files
    from the control.tar.gz tarball in packages.

wd [-e] <regex>
workdir [-e] <regex>
    Locate the Yocto Project's workdir for <regex>.  <regex> is
    implicitly surrounded by '.*', unless -e is provided.

l [-e] [-H] <recipe pattern> <log pattern>
log [-e] [-H] <recipe pattern> <log pattern>
    Show the log files for <recipe>.  -e is only applied to
    <recipe pattern>.  <log pattern> is always implicitly surrounded
    by '.*'.  If -H ("human readable") is given on the command line,
    ye will try to make the lines that contain calls to gcc/g++ look
    more readable.

r [-e] <recipe pattern> <run script pattern>
run [-e] <recipe pattern> <run script pattern>
    Show the log files for <recipe>.  -e is only applied to
    <recipe pattern>.  <run script pattern> is always implicitly
    surrounded by '.*'.

g <args>
grep <args>
    Run 'repo grep <args>'.

sg <args>
sysroot-grep <args>
   Run 'grep -r <args> $BUILDDIR/tmp/sysroots/$MACHINE'.

glg [-n <num commits> ] [-i] <regex>
git-log-grep [-n <num commits> ] [-i] <regex>
   Run "git log -n <num commits> --oneline | grep <regex>" on all the
   repositories and prompt the user for the commit to show.
   If -n is not provided, 1000 will be used.  If -i is provided, search
   will be case insensitive.

bh [-d] <revisions back>
buildhistory [-d] <revisions back>
    Show changes in buildhistory <revisions back> (a positive integer).
    If -d is given, show the raw git diff output.

d [-e] <regex>
doc [-e] <regex>
    Search variable names in the reference manual that match the given
    expression <regex> and show the documentation for the selected
    match.  <regex> is case insensitive and implicitly surrounded by
    '.*'.  -e disables the implicit use of '.*' around the given
    <regex>.

x <recipe> <variable>
expand <recipe> <variable>
    Expand BitBake's variable <variable> in the context of <recipe> and
    show the final value and the recursive expansion of all variables
    and expressions involved.

cd [<dir shortcut>]
    Change to <dir shortcut>.  The following <dir shortcut> options are
    available:

    top
        Change to project's TOPDIR

    wd [<recipe>]
        Change to <recipe>'s WORKDIR or to BUILDDIR/tmp/deploy/work if
        <recipe> is not provided

    bd
        Change to BUILDDIR

    sd
        Change to the sysroot directory for MACHINE

    src [<recipe>]
        Change to <recipes>'s source dir or to TOPDIR/sources
        if <recipe> is not provided

    img
        Change to BUILDDIR/tmp/deploy/MACHINE/image/

    pkg
        Change to BUILDDIR/tmp/deploy/PKG_TYPE/image/

    manifest
        Change to TOPDIR/.repo/manifests

    When called without arguments, ye cd will change to BUILDDIR.

    To use this feature, source'ing the ye-cd shell helper is required.
....

All the operations performed by the toplevel commands `find`,
`sysroot-find`, `pkg-find`, `workdir`, `log` and `run` are related to
locating files and directories in the project's directory structure.

Each command handles a special case:

`find`:: Search for files in the directory where the source files are
stored (`<yocto root dir>/sources`).

`sysroot-find`:: Search for files in the sysroots directories
(`$BUILDDIR/tmp/sysroots`).

`pkg-find`:: Search for package files in the deploy directory for
packages (`$BUILDDIR/tmp/deploy/<pkg format>`).

`workdir`:: Search for recipes' work directories in the work directory
(`$BUILDDIR/tmp/work`).

`log`:: Search for task log files in the work directory
(`$BUILDDIR/<arch>/<recipe>/<version>/temp`) for the recipes that
match the given recipe pattern.

`run`:: Search for task run script files in the work directory
(`$BUILDDIR/<arch>/<recipe>/<version>/temp`) for the recipes that
match the given recipe pattern.

`grep`:: A wrapper around `repo grep`, which interactively prompts for
actions on files that match the search patterns.

`buildhistory`:: A wrapper for either `buildhistory-diff` or `git
diff` in the buildhistory directory (when `-d` is provided).  The
mandatory numeric argument is the number of revisions back the diff
should be generated from.

All commands, except `buildhistory` and `expand` use a regular
expression pattern (`<regex>`) as argument, which is matched against
filenames only if they don't contain a slash (`/`) character.  If they
contain a slash character, it means you probably want to search for a
full or partial paths with at least one directory part.  In this case,
`ye` will match the pattern agains the full file path.

All commands, except `grep`, `buildhistory`, `expand` and `cd`, accept
a `-e` option, which indicates the search is to be _exact_.  Without
this option `ye` will surround the provided pattern by `.*`, which
means matching anything before and after the provided pattern (which
will be matched against the filename or the full path, depending if
the given pattern contains a slash or not).

The matches will be highlighted in red on the output.

Except for the `workdir`, `buildhistory` and `expand` commands, all
`ye` commands are (or may be) interactive.  After locating files that
match the given pattern, `ye` will prompt you to select one of the
matches and, next, what to do with it.  In case the standard output is
not a terminal (e.g., a file or a pipe), interactive commands will
just print the results to the standard output (no prompt for action
will be displayed).

Example:

....
$ ye f flex
[0] ~/yocto/sources/poky/meta/recipes-devtools/flex/flex.inc [0]
[1] ~/yocto/sources/poky/meta/recipes-devtools/flex/flex_2.5.35.bb [1]
Option (ENTER to cancel): 1
[v] View
[e] Edit
Option (ENTER to cancel): v
     1  require flex.inc
     2  PR = "r3"
     3  LICENSE="BSD"
     4  LIC_FILES_CHKSUM = "file://COPYING;md5=e4742cf92e89040b39486a6219b68067"
     5  BBCLASSEXTEND = "native nativesdk"
     6  
     7  SRC_URI += "file://avoid-FORTIFY-warnings.patch \
     8              file://int-is-not-the-same-size-as-size_t.patch"
     9  
    10  SRC_URI[md5sum] = "10714e50cea54dc7a227e3eddcd44d57"
    11  SRC_URI[sha256sum] = "0becbd4b2b36b99c67f8c22ab98f7f80c9860aec70..."
....

NOTE: `ye` also allows you to use shortcuts for selecting options and
actions at the same prompt.  In the example above, we typed `0 ENTER`
to select `flex.inc`, then `0 ENTER` to select the `View` action.  The
shortcut would be `0v ENTER` in the file selection prompt.  For
`Edit`, the shortcut would be `0e ENTER`.

Shortcuts for actions may also be specified on the command line.  Some
commands are actually shortcuts to `<command> -> <action>`:

`view` (`v`):: shortcut to `find -> view`
`edit` (`e`):: shortcut to `find -> edit`
`pkg-view` (`pv`):: shortcut to `pkg-find -> view`
`pkg-info` (`pi`):: shortcut to `pkg-find -> info`

In case the pattern given as argument to `find` or `pkg-find` matches
multiple files or packages, a prompt for selecting files will be
displayed if the standard output is a terminal.  If the standard
output is not a terminal, all matches will be printed.

Except for the `find` and `grep` commands, all commands expect the
`BUILDDIR` environment variable to be set in the environment.  This
variable is automatically set by the `setup-environment` script
provided by O.S. Systems for the Yocto Project-based projects.


== Configuration

`ye` allows you to customize the pager and the editor it uses for
displaying and editing files, respectively.

The configuration is via environment variables.  `ye` uses `YE_PAGER`
and `YE_EDITOR` for pager and editor, respectively.

For the editor, `ye` first checks if `YE_EDITOR` is set in the
environment.  If it is not set, it checks the `EDITOR` environment
variable.  If it is not set, it resorts to `emacs`.  If `emacs` cannot
be found, you'll get an error.

For the pager, `ye` first checks if `YE_PAGER` is set in the
environment.  If it is not set, it checks the `PAGER` environment
variable.  If it is not set, it resorts to `less -N %s`.  If `less`
cannot be found, you'll get an error.

`%s` can be used as a placeholder for the file to act upon.


== Requirements

A Python installation and the directory structure in the layout
created by O.S. System's Yocto Project-based platforms.

`ye` has been more extensively tested with Python version 2.7.3, but
it should work with other recent Python 2.x versions and with Python
3.x.

For the `doc` command, the http://lxml.de/[lxml] module for Python is
required.

For the `cd` command, a Bourne-compatible shell is required.

== License

`ye` is distributed under the GNU Affero General Public License.  See
the `LICENSE` file for the full license text.
